<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>696aa323-ee87-403c-9cd7-13e688ed95bd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MiniBooking.Application\MiniBooking.Application.csproj" />
    <ProjectReference Include="..\MiniBooking.Infrastructure\MiniBooking.Infrastructure.csproj" />
  </ItemGroup>

</Project>
